Web-admin/Admin_Page/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_Page;

namespace Admin_Page.Controllers
{
    public class RequestsController : Controller
    {
        private AEW_DEVEntities db = new AEW_DEVEntities();

        // GET: Requests
        public ActionResult Index()
        {
            var idStr = Request.QueryString["Stores"];
            var statusStr = Request.QueryString["Status"];

            // Lấy data
            // Lấy toàn bộ thể loại:
            List<Store> stores = db.Stores.ToList();
            List<CheckFace> checks = db.CheckFaces.ToList();
            var storeId = stores.FirstOrDefault<Store>().ID;
            var status = 1;
            if (idStr != null && statusStr != null)
            {
                storeId = int.Parse(idStr);
                status = int.Parse(statusStr);
            }
            // Tạo SelectList
            SelectList storesList = new SelectList(stores, "ID", "NAME");
            SelectList statusList = new SelectList(checks, "Statuts", "Statuts");
            // Set vào ViewBag
            ViewBag.Statuts = statusList;
            ViewBag.CategoryList = storesList;
            var checkFaces = db.CheckFaces.Include(c => c.Employee).Include(c => c.FaceScanMachine).Include(c => c.WorkingShift).Where(s => s.StoreId == storeId).Where(c => c.Statuts == status);
            return View(checkFaces.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckFace checkFace = db.CheckFaces.Find(id);
            if (checkFace == null)
            {
                return HttpNotFound();
            }
            return View(checkFace);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name");
            ViewBag.FaceScanMachineId = new SelectList(db.FaceScanMachines, "Id", "MachineCode");
            ViewBag.WorkShiftId = new SelectList(db.WorkingShifts, "Id", "UpdatePerson");
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FaceScanMachineId,EmployeeId,CreateTime,Mode,Active,StoreId,IsUpdated,Image,IpWifi,GPS,WorkShiftId,Content,Statuts")] CheckFace checkFace)
        {
            if (ModelState.IsValid)
            {
                db.CheckFaces.Add(checkFace);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name", checkFace.EmployeeId);
            ViewBag.FaceScanMachineId = new SelectList(db.FaceScanMachines, "Id", "MachineCode", checkFace.FaceScanMachineId);
            ViewBag.WorkShiftId = new SelectList(db.WorkingShifts, "Id", "UpdatePerson", checkFace.WorkShiftId);
            return View(checkFace);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(int? id)
        {
            var statusStr = Request.QueryString["Status"];
            //[Bind(Include = "Id,Statuts")] CheckFace checkFace
            if (ModelState.IsValid)
            {
                var data = db.CheckFaces.Find(id);
                data.Statuts = int.Parse(statusStr);
                db.Entry(data).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var checkFaces = db.CheckFaces.Include(c => c.Employee).Include(c => c.FaceScanMachine).Include(c => c.WorkingShift).Where(s => s.StoreId == 3).Where(c => c.Statuts == 1);
            return View(checkFaces);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FaceScanMachineId,EmployeeId,CreateTime,Mode,Active,StoreId,IsUpdated,Image,IpWifi,GPS,WorkShiftId,Content,Statuts")] CheckFace checkFace)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkFace).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name", checkFace.EmployeeId);
            ViewBag.FaceScanMachineId = new SelectList(db.FaceScanMachines, "Id", "MachineCode", checkFace.FaceScanMachineId);
            ViewBag.WorkShiftId = new SelectList(db.WorkingShifts, "Id", "UpdatePerson", checkFace.WorkShiftId);
            return View(checkFace);
        }*/

        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()
        {
            var idStr = Request.QueryString["ID"];
            var statusStr = Request.QueryString["Status"];
            //[Bind(Include = "Id,Statuts")] CheckFace checkFace
            if (ModelState.IsValid)
            {
                var data = db.CheckFaces.Find(int.Parse(idStr));
                data.Statuts = int.Parse(statusStr);
                db.Entry(data).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            var checkFaces = db.CheckFaces.Include(c => c.Employee).Include(c => c.FaceScanMachine).Include(c => c.WorkingShift).Where(s => s.StoreId == 3).Where(c => c.Statuts == 1);
            return View(checkFaces);
        }*/

        // GET: Requests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckFace checkFace = db.CheckFaces.Find(id);
            if (checkFace == null)
            {
                return HttpNotFound();
            }
            return View(checkFace);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CheckFace checkFace = db.CheckFaces.Find(id);
            db.CheckFaces.Remove(checkFace);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web-admin/Admin_Page/Views/Requests/Create.cshtml
@model Admin_Page.CheckFace

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckFace</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FaceScanMachineId, "FaceScanMachineId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FaceScanMachineId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FaceScanMachineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StoreId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StoreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsUpdated)
                    @Html.ValidationMessageFor(model => model.IsUpdated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IpWifi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IpWifi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IpWifi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GPS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GPS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GPS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkShiftId, "WorkShiftId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WorkShiftId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkShiftId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statuts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statuts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statuts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web-admin/Admin_Page/Views/Requests/Delete.cshtml
@model Admin_Page.CheckFace

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CheckFace</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IpWifi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IpWifi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statuts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statuts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaceScanMachine.MachineCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaceScanMachine.MachineCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkingShift.UpdatePerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkingShift.UpdatePerson)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web-admin/Admin_Page/Views/Requests/Details.cshtml
@model Admin_Page.CheckFace

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CheckFace</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StoreId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StoreId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IpWifi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IpWifi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GPS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GPS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statuts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statuts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FaceScanMachine.MachineCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FaceScanMachine.MachineCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorkingShift.UpdatePerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorkingShift.UpdatePerson)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Web-admin/Admin_Page/Views/Requests/Edit.cshtml
@model Admin_Page.CheckFace

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CheckFace</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FaceScanMachineId, "FaceScanMachineId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FaceScanMachineId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FaceScanMachineId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StoreId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StoreId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsUpdated)
                    @Html.ValidationMessageFor(model => model.IsUpdated, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IpWifi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IpWifi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IpWifi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GPS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GPS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GPS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkShiftId, "WorkShiftId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WorkShiftId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkShiftId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Statuts, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Statuts, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Statuts, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Web-admin/Admin_Page/Views/Requests/Index.cshtml
@model IEnumerable<Admin_Page.CheckFace>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Request Management</h2>
@using (Html.BeginForm("Index", "Requests", FormMethod.Get, new { @class = "dataTables_length d-flex" }))
{
    @Html.DropDownList("Stores", (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select store", new { @class = "custom-select custom-select-sm form-control form-control-sm", required = "required" })
    <select id="Status" name="Status" class="custom-select custom-select-sm form-control form-control-sm">
        <option value="1">New</option>
        <option value="2">Approved</option>
        <option value="3">Rejected</option>
    </select>
    <input type="submit" value="Search">
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreateTime)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Mode)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.StoreId)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.IsUpdated)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.IpWifi)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.GPS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Statuts)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Employee.Name)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.FaceScanMachine.MachineCode)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.WorkingShift.UpdatePerson)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Mode)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.StoreId)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.IsUpdated)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.IpWifi)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.GPS)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.Statuts)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Name)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.FaceScanMachine.MachineCode)
            </td>
            <td hidden>
                @Html.DisplayFor(modelItem => item.WorkingShift.UpdatePerson)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
                @if (item.Statuts == 1)
                {
                    <input type="button" value="Aprove" class="btn btn-success" onclick="location.href='@Url.Action("Edit", "Requests", new { ID = item.Id, Status = 2 })'" />
                    <input type="button" value="Reject" class="btn btn-danger" onclick="location.href='@Url.Action("Edit", "Requests", new { ID = item.Id, Status = 3 })'" />
                }
                else if (item.Statuts == 2)
                {
                    <input type="button" value="Aproved" class="btn btn-success" />
                }
                else
                {
                    <input type="button" value="Rejected" class="btn btn-danger" />
                }
            </td>
        </tr>
    }

</table>