Web-admin/Admin_Page/Controllers/StoreController.cs
using Admin_Page.Environment;
using Admin_Page.Filters;
using Admin_Page.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;
using PagedList; // thêm thư viện này


namespace Admin_Page.Controllers
{
    [UserAuthenticationFilter]
    public class StoreController : Controller
    {
        // GET: Store
        dynamic mymodel = new ExpandoObject();
        //TempDataDictionary["page"] = pageSize;
        public async Task<ActionResult> GenerateCode()
        {
                using (var client = new HttpClient())
            {
                var StoreList = new List<StoreViewModel>();
                var data = new BaseModel<IEnumerable<StoreViewModel>>();
                //Passing service base url  
                client.BaseAddress = new Uri(ApiUrl.baseUrl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource get all stores using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(ApiUrl.GetListStores);
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var StoreResponse = Res.Content.ReadAsStringAsync().Result;
                    
                    //Deserializing the response recieved from web api and storing into the store list  
                    data = JsonConvert.DeserializeObject<BaseModel<IEnumerable<StoreViewModel>>>(StoreResponse);    
                    StoreList = (List<StoreViewModel>)data.Data;
                    
                    //returning the store list to view  
                    TempData["Count"] = StoreList.Count;
                    TempData["myList"] = StoreList;
                    mymodel.Stores = StoreList;
                    mymodel.Codes = null;
                    mymodel.SelectedStoreId = null;
                    return View(mymodel);
                }

                return View();
            }

        }

        private async void GetListStore()
        {
            //return View();
            List<StoreViewModel> StoreList = new List<StoreViewModel>();
            BaseModel<IEnumerable<StoreViewModel>> data = new BaseModel<IEnumerable<StoreViewModel>>();
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(ApiUrl.baseUrl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource get all stores using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(ApiUrl.GetListStores);
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var StoreResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the store list  
                    data = JsonConvert.DeserializeObject<BaseModel<IEnumerable<StoreViewModel>>>(StoreResponse);
                    StoreList = (List<StoreViewModel>)data.Data;

                    //returning the store list to view  
                    TempData["myList"] = StoreList;
                } 
            }
        }
       private string getName(string id)
        {
            var list = TempData["myList"] as List<StoreViewModel>;
            foreach (var item in list)
            {
                if (item.Id.Equals(id))
                {
                    return item.Name;
                }
            }
            return null;

        }

        public async Task<ActionResult> AuthorizedCode()
        {
            var list = TempData["myList"] as List<StoreViewModel>;
            string storeId = Request.Form["Select_Store"];
            using (var client = new HttpClient())
            {
                var data = new BaseModel<StoreViewModel>();
                StoreViewModel code = new StoreViewModel();
                client.BaseAddress = new Uri(ApiUrl.baseUrl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

               HttpResponseMessage Res = await client.GetAsync(ApiUrl.AuthorizeCodeUrl + storeId); //API controller name


                if (Res.IsSuccessStatusCode)
                {
                    var result =  Res.Content.ReadAsStringAsync().Result;
                    data = JsonConvert.DeserializeObject<BaseModel<StoreViewModel>>(result);
                    code = data.Data;
                    if (code != null)
                    {
                        mymodel.Codes = code;
                        mymodel.Stores = list;
                        mymodel.SelectedStoreId = storeId;
                        TempData["myList"] = list;
                        return View("GenerateCode", mymodel);
                    }
                    
                }
                
                
            }
            mymodel.Stores = list;
            mymodel.SelectedStoreId = storeId;
            mymodel.Codes = null;
            TempData["myList"] = list;
            return View("GenerateCode", mymodel);

        }

        private async Task<List<StoreViewModel>> GetStoreViewsAsync(string sortProperty, string orderBy,string searchString)
        {
            List<StoreViewModel> StoreList = new List<StoreViewModel>();
            BaseModel<IEnumerable<StoreViewModel>> data = new BaseModel<IEnumerable<StoreViewModel>>();
            string search = "";
            if (!String.IsNullOrEmpty(searchString)) search = searchString;
            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(ApiUrl.baseUrl);
                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource get all stores using HttpClient  
                //getStoresDes/name/desc
                //HttpResponseMessage Res = await client.GetAsync(ApiUrl.GetListStores);
                HttpResponseMessage Res = await client.GetAsync(ApiUrl.GetStores + sortProperty + "/" + orderBy+"/" + search);
                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var StoreResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the store list  
                    data = JsonConvert.DeserializeObject<BaseModel<IEnumerable<StoreViewModel>>>(StoreResponse);
                    StoreList = (List<StoreViewModel>)data.Data;

                    //returning the store list to view  
                    TempData["myList"] = StoreList;
                    return StoreList;
                }
                return StoreList;
            }

        }

        public async Task<ActionResult> Index(int? size, int? page, string sortProperty, string sortOrder, string searchString)
    {
            List<StoreViewModel> StoreList = new List<StoreViewModel>();


        // 1. Tạo biến ViewBag gồm sortOrder, searchValue, sortProperty và page
        if (sortOrder == "asc") ViewBag.sortOrder = "desc";
        if (sortOrder == "desc") ViewBag.sortOrder = "";
        if (sortOrder == "") ViewBag.sortOrder = "asc";
        ViewBag.searchValue = searchString;
        ViewBag.sortProperty = sortProperty;
        ViewBag.page = page;

        // 2. Tạo danh sách chọn số trang
        List<SelectListItem> items = new List<SelectListItem>();
        items.Add(new SelectListItem { Text = "5", Value = "5" });
        items.Add(new SelectListItem { Text = "10", Value = "10" });
        items.Add(new SelectListItem { Text = "20", Value = "20" });


        // 2.1. Thiết lập số trang đang chọn vào danh sách List<SelectListItem> items
        foreach (var item in items)
        {
            if (item.Value == size.ToString()) item.Selected = true;
        }
        ViewBag.size = items;
        ViewBag.currentSize = size;

        // 3. Lấy tất cả tên thuộc tính của lớp Link (LinkID, LinkName, LinkURL,...)
        var properties = typeof(StoreViewModel).GetProperties();
        List<Tuple<string, bool, int>> list = new List<Tuple<string, bool, int>>();
        foreach (var item in properties)
        {
            int order = 999;
            var isVirtual = item.GetAccessors()[0].IsVirtual;

                if (item.Name == "StoreCode") order = 2;
                else if (item.Name == "Id") order = 1;
                else if (item.Name == "Name") order = 3;
                else if (item.Name == "Address") order = 4;
                else if (item.Name == "AuthorizeCode") order = 5;
                else continue;
            if (item.Name == "ShortName") continue; // Không hiển thị cột này

Web-admin/Admin_Page/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_Page;

namespace Admin_Page.Controllers
{
    public class StoresController : Controller
    {
        private AEW_DEVEntities db = new AEW_DEVEntities();

        // GET: Stores
        public ActionResult Index()
        {
            var stores = db.Stores.Include(s => s.Brand);
            return View(stores.ToList());
        }

        // GET: Stores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // GET: Stores/Create
        public ActionResult Create()
        {
            ViewBag.BrandId = new SelectList(db.Brands, "Id", "BrandName");
            return View();
        }

        // POST: Stores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Address,Lat,Lon,isAvailable,Email,Phone,Fax,CreateDate,Type,RoomRentMode,ReportDate,ShortName,GroupId,OpenTime,CloseTime,DefaultAdminPassword,HasProducts,HasNews,HasImageCollections,HasMultipleLanguage,HasWebPages,HasCustomerFeedbacks,BrandId,HasOrder,HasBlogEditCollections,LogoUrl,FbAccessToken,StoreFeatureFilter,RunReport,AttendanceStoreFilter,StoreCode,PosId,StoreConfig,DefaultDashBoard,District,Province,Active,PaymentTypeApply")] Store store)
        {
            if (ModelState.IsValid)
            {
                db.Stores.Add(store);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandId = new SelectList(db.Brands, "Id", "BrandName", store.BrandId);
            return View(store);
        }

        // GET: Stores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandId = new SelectList(db.Brands, "Id", "BrandName", store.BrandId);
            return View(store);
        }

        // POST: Stores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Address,Lat,Lon,isAvailable,Email,Phone,Fax,CreateDate,Type,RoomRentMode,ReportDate,ShortName,GroupId,OpenTime,CloseTime,DefaultAdminPassword,HasProducts,HasNews,HasImageCollections,HasMultipleLanguage,HasWebPages,HasCustomerFeedbacks,BrandId,HasOrder,HasBlogEditCollections,LogoUrl,FbAccessToken,StoreFeatureFilter,RunReport,AttendanceStoreFilter,StoreCode,PosId,StoreConfig,DefaultDashBoard,District,Province,Active,PaymentTypeApply")] Store store)
        {
            if (ModelState.IsValid)
            {
                db.Entry(store).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandId = new SelectList(db.Brands, "Id", "BrandName", store.BrandId);
            return View(store);
        }

        // GET: Stores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Store store = db.Stores.Find(id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Store store = db.Stores.Find(id);
            db.Stores.Remove(store);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web-admin/Admin_Page/Views/Store/AuthorizedCode.cshtml
@model Admin_Page.Models.AuthorizeCodeViewModel

@{
    ViewBag.Title = "AuthorizedCode";
}

@{
        if (Model != null)
        {
            <p class="h1 mt-5 text-center">@Model.code</p>
            <p class="h1 mt-5 text-center"></p>
            <p class="h1 mt-5 text-center">@Model.createDate</p>
            <p class="h1 mt-5 text-center">@Model.expiredDate</p>
        }
    }

Web-admin/Admin_Page/Views/Store/GenerateCode.cshtml
@model dynamic
@*@model IEnumerable<Admin_Page.Models.StoreViewModel>*@
@{
    ViewBag.Title = "GenerateCode";

}

<h2>Generate Code</h2>
<div class="text-center">
    @using (Html.BeginForm("AuthorizedCode", "Store", FormMethod.Post, new { @class = "vertical d-flex bd-highlight mb-2 align-items-center" }))
    {
    <select name="Select_Store" class="selectpicker form-control mb-lg-n2 ml-4" id="StoredId" required>
        @if (Model.SelectedStoreId == null)
        {
            <option disabled="disabled" selected value="0">---Select Your Store---</option>
        }
        @foreach (var item in Model.Stores)
        {
            if ((Model.SelectedStoreId != null) && ((string)Model.SelectedStoreId).Equals(item.Id.ToString()))
            {
                <option class="active" selected="selected" value="@item.Id">@item.Name</option>
            }
            else
            {
                <option value="@item.Id">@item.Name</option>
            }

        }
    </select>
        <button type="submit" class="btn btn-outline-secondary ml-5">Generate</button>
    }


</div>

@*@{
    Html.RenderAction("AuthorizedCode");}*@

@{
    if (Model.Codes != null)
    {
       // <h1>@Model.StoreName</h1>
        var newCode = Model.Codes;
        <p class="h1 mt-5 text-center">@newCode.AuthorizeCode</p>
       
    }
}

Web-admin/Admin_Page/Views/Store/GetAllStoreView.cshtml
@model IEnumerable<Admin_Page.Models.StoreViewModel>
<!-- Thêm thư viện -->
@*@model PagedList.IPagedList<Admin_Page.Models.StoreViewModel>
    @using PagedList.Mvc;*@
<!-- Kết thúc-->
<!-- DataTales Example -->
<h1>Store Management  </h1>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @*<div class="mb-2 ">
                    <div class="dataTables_length d-flex">
                        <label>
                            Show:
                        </label>
                        @using (Html.BeginForm("GetAllStoreView", "Store", new { @id = "myForm" }))
                        {
                            <select class="custom-select custom-select-sm form-control form-control-sm" name="pageSize" id="pageSize" onchange="this.form.submit()">
                                <option selected value="5">5</option>
                                <option value="10">10</option>
                                <option value="20">20</option>
                            </select>
                        }

                        <label>
                            entries
                        </label>
                    </div>

                </div>*@
            <div class="d-flex mb-3">
                <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
                    @using (Html.BeginForm("GetAllStoreView", "Store", new { sortOrder = ViewBag.NameSortParm, size = ViewBag.currentSize }, FormMethod.Get, new { @class = "dataTables_length d-flex" }))
                    {<label class="mr-2">
                            Show:
                        </label>
                        <p>
                            @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();", @class = "custom-select custom-select-sm form-control form-control-sm" })
                        </p>
                        <label class="ml-2">
                            entries
                        </label>
                    }
                </div>
                <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
                    <!-- Another variation with a button -->
                    <form action="GetAllStoreView" method="get">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="----- Search -----" id="txtValue" name="ValueSearch">
                            <div class="input-group-append">
                                <button class="btn btn-secondary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>@Html.ActionLink("Store Code", "GetAllStoreView", new { sortOrder = ViewBag.NameSortParm, size = ViewBag.currentSize })</th>
                        <th>Store Name</th>
                        <th>Address</th>
                        <th>ShortName</th>
                        <th>Waiting ...</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>No.</th>
                        <th>Store Code</th>
                        <th>Store Name</th>
                        <th>Address</th>
                        <th>ShortName</th>
                        <th>Waiting ...</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            
                                <td>@*@Url.Action("Edit","Store", new { @id = item.Id})*@
                                    @Html.DisplayFor(modelItem => item.Id)</td>
                                <td>@Html.DisplayFor(modelItem => item.StoreCode)</td>
                                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.Address)</td>
                                <td>@Html.DisplayFor(modelItem => item.ShortName)</td>
                                <td>Test</td>
                        </tr>
                    }


                </tbody>
            </table>
            @*<div>
                    <ul class="pagination justify-content-end">
                        <li class="paginate_button page-item previous" id="dataTable_previous">
                            <a href="#" aria-controls="dataTable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                        </li>
                        <li class="paginate_button page-item ">
                            <a href="#" aria-controls="dataTable" data-dt-idx="1" tabindex="0" class="page-link">1</a>
                        </li>
                        <li class="paginate_button page-item ">
                            <a href="#" aria-controls="dataTable" data-dt-idx="2" tabindex="0" class="page-link">2</a>
                        </li>
                        <li class="paginate_button page-item ">
                            <a href="#" aria-controls="dataTable" data-dt-idx="3" tabindex="0" class="page-link">3</a>
                        </li>
                        <li class="paginate_button page-item ">
                            <a href="#" aria-controls="dataTable" data-dt-idx="4" tabindex="0" class="page-link">4</a>
                        </li>
                        <li class="paginate_button page-item ">
                            <a href="#" aria-controls="dataTable" data-dt-idx="5" tabindex="0" class="page-link">5</a>
                        </li>
                        <li class="paginate_button page-item active">
                            <a href="#" aria-controls="dataTable" data-dt-idx="6" tabindex="0" class="page-link">6</a>
                        </li>
                        <li class="paginate_button page-item next disabled" id="dataTable_next">
                            <a href="#" aria-controls="dataTable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
                        </li>
                    </ul>
                </div>*@
            @*<br />
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("GetAllStoreView",
                    new { page }))*@
        </div>
    </div>
</div>
<script src="~/Assets/js/sb-admin-2.min.js"></script>
<script type="text/javascript">
        $(document).ready(function () {
            $('#txtValue').autocomplete({
                source: '@Url.Action("GetAllStoreView", "Store")'
            });
        });
</script>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Styles.Render("~/Assest/css/search.css")