Web-admin/Admin_Page/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_Page;

namespace Admin_Page.Controllers
{
    public class EmployeesController : Controller
    {
        private AEW_DEVEntities db = new AEW_DEVEntities();

        // GET: Employees
        public ActionResult Index()
        {
            var idStr = Request.QueryString["Stores"];

            // Lấy data
            // Lấy toàn bộ thể loại:
            List<Store> stores = db.Stores.ToList();
            var storeId = stores.FirstOrDefault<Store>().ID;
            if (idStr != null)
            {
                storeId = int.Parse(idStr);
            }
            // Tạo SelectList
            SelectList storesList = new SelectList(stores, "ID", "NAME");
            // Set vào ViewBag
            ViewBag.CategoryList = storesList;
            var employees = db.Employees.Include(e => e.EmployeeGroup).Where(s => s.MainStoreId == storeId);
            return View(employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeGroupId = new SelectList(db.EmployeeGroups, "Id", "CodeGroup");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Role,EmpEnrollNumber,MainStoreId,Address,Phone,Active,BrandId,Salary,Status,DateStartWork,EmployeeGroupId,EmployeeCode,EmployeeRegency,DateOfBirth,EmployeeSex,PersonalCardId,DatePersonalCard,PlaceOfPersonalCard,PhoneNumber,Email,MainAddress,EmployeeHometown,EmployeePlaceBorn,DateQuitWork,ReasonQuit,PersonalIncomTax,MaritalStatus,SocialInsuranceNumber,BankNumber,Bank,EducationType,EducationStatus,EducationQualify,Specialized,SchoolName,CourseYear,FormOfTraining,ContactOne,ContactTwo,Image")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeGroupId = new SelectList(db.EmployeeGroups, "Id", "CodeGroup", employee.EmployeeGroupId);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeGroupId = new SelectList(db.EmployeeGroups, "Id", "CodeGroup", employee.EmployeeGroupId);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Role,EmpEnrollNumber,MainStoreId,Address,Phone,Active,BrandId,Salary,Status,DateStartWork,EmployeeGroupId,EmployeeCode,EmployeeRegency,DateOfBirth,EmployeeSex,PersonalCardId,DatePersonalCard,PlaceOfPersonalCard,PhoneNumber,Email,MainAddress,EmployeeHometown,EmployeePlaceBorn,DateQuitWork,ReasonQuit,PersonalIncomTax,MaritalStatus,SocialInsuranceNumber,BankNumber,Bank,EducationType,EducationStatus,EducationQualify,Specialized,SchoolName,CourseYear,FormOfTraining,ContactOne,ContactTwo,Image")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeGroupId = new SelectList(db.EmployeeGroups, "Id", "CodeGroup", employee.EmployeeGroupId);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web-admin/Admin_Page/Views/Employees/Delete.cshtml
@model Admin_Page.Employee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpEnrollNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpEnrollNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainStoreId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MainStoreId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrandId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrandId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateStartWork)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateStartWork)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeRegency)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeRegency)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeSex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeSex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalCardId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalCardId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePersonalCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePersonalCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlaceOfPersonalCard)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlaceOfPersonalCard)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MainAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MainAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeHometown)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeHometown)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeePlaceBorn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeePlaceBorn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateQuitWork)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateQuitWork)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReasonQuit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReasonQuit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalIncomTax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalIncomTax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaritalStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaritalStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SocialInsuranceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SocialInsuranceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EducationType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EducationStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EducationQualify)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EducationQualify)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Specialized)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Specialized)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SchoolName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SchoolName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FormOfTraining)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FormOfTraining)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactOne)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactOne)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactTwo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactTwo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeGroup.CodeGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeGroup.CodeGroup)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web-admin/Admin_Page/Views/Employees/Index.cshtml
@model IEnumerable<Admin_Page.Employee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Employees Management</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
    @using (Html.BeginForm("Index", "Employees", FormMethod.Get, new { @class = "dataTables_length d-flex" }))
    {
        @Html.DropDownList("Stores", (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select store", new { @onchange = "this.form.submit();", @class = "custom-select custom-select-sm form-control form-control-sm" })
    }
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmpEnrollNumber)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.MainStoreId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.BrandId)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.DateStartWork)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmployeeCode)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmployeeRegency)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmployeeSex)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.PersonalCardId)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.DatePersonalCard)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.PlaceOfPersonalCard)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.MainAddress)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmployeeHometown)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmployeePlaceBorn)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.DateQuitWork)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.ReasonQuit)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.PersonalIncomTax)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.MaritalStatus)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.SocialInsuranceNumber)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.BankNumber)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Bank)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EducationType)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EducationStatus)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EducationQualify)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.Specialized)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.SchoolName)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.CourseYear)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.FormOfTraining)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.ContactOne)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.ContactTwo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th hidden>
            @Html.DisplayNameFor(model => model.EmployeeGroup.CodeGroup)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Role)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmpEnrollNumber)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.MainStoreId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.BrandId)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.DateStartWork)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmployeeCode)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmployeeRegency)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmployeeSex)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.PersonalCardId)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.DatePersonalCard)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.PlaceOfPersonalCard)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.MainAddress)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmployeeHometown)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmployeePlaceBorn)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.DateQuitWork)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.ReasonQuit)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.PersonalIncomTax)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.MaritalStatus)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.SocialInsuranceNumber)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.BankNumber)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Bank)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EducationType)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EducationStatus)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EducationQualify)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.Specialized)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.SchoolName)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.CourseYear)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.FormOfTraining)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.ContactOne)
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.ContactTwo)
        </td>
        <td>
            <img src="data:image/png;base64,@Html.DisplayFor(modelItem => item.Image)" />
        </td>
        <td hidden>
            @Html.DisplayFor(modelItem => item.EmployeeGroup.CodeGroup)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) 
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>