Web-admin/Admin_Page/Controllers/WorkingShiftsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin_Page;

namespace Admin_Page.Controllers
{
    public class WorkingShiftsController : Controller
    {
        private AEW_DEVEntities db = new AEW_DEVEntities();

        // GET: WorkingShifts
        public ActionResult Index()
        {
            var idStr = Request.QueryString["Stores"];
            
            // Lấy data
            // Lấy toàn bộ thể loại:
            List<Store> stores = db.Stores.ToList();
            var storeId = stores.FirstOrDefault<Store>().ID;
            if (idStr != null)
            {
                storeId = int.Parse(idStr);
            }
            // Tạo SelectList
            SelectList storesList = new SelectList(stores, "ID", "NAME");
            // Set vào ViewBag
            ViewBag.CategoryList = storesList;
            var workingShifts = db.WorkingShifts.Include(w => w.Employee).Include(w => w.Store).Where(w => w.Store.ID == storeId);
            return View(workingShifts.ToList());

        }

        // GET: WorkingShifts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkingShift workingShift = db.WorkingShifts.Find(id);
            if (workingShift == null)
            {
                return HttpNotFound();
            }
            return View(workingShift);
        }

        // GET: WorkingShifts/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name");
            ViewBag.StoreId = new SelectList(db.Stores, "ID", "Name");
            return View();
        }

        // POST: WorkingShifts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EmployeeId,Active,CheckMin,CheckMax,TotalWorkTime,Status,ShiftStart,ShiftEnd,CheckInTime,UpdatePerson,ProcessingStatus,Note,StoreId,TimeFramId,BreakTime,RequestedCheckOut,RequestedCheckIn,IsRequested,ApprovePerson,NoteRequest,LastCheckBeforeShift,FirstCheckAfterShift,IsOverTime,InMode,OutMode,BreakCount,CheckInExpandTime,CheckOutExpandTime,ComeLateExpandTime,LeaveEarlyExpandTime")] WorkingShift workingShift)
        {
            if (ModelState.IsValid)
            {
                db.WorkingShifts.Add(workingShift);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name", workingShift.EmployeeId);
            ViewBag.StoreId = new SelectList(db.Stores, "ID", "Name", workingShift.StoreId);
            return View(workingShift);
        }

        // GET: WorkingShifts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkingShift workingShift = db.WorkingShifts.Find(id);
            if (workingShift == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name", workingShift.EmployeeId);
            ViewBag.StoreId = new SelectList(db.Stores, "ID", "Name", workingShift.StoreId);
            return View(workingShift);
        }

        // POST: WorkingShifts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EmployeeId,Active,CheckMin,CheckMax,TotalWorkTime,Status,ShiftStart,ShiftEnd,CheckInTime,UpdatePerson,ProcessingStatus,Note,StoreId,TimeFramId,BreakTime,RequestedCheckOut,RequestedCheckIn,IsRequested,ApprovePerson,NoteRequest,LastCheckBeforeShift,FirstCheckAfterShift,IsOverTime,InMode,OutMode,BreakCount,CheckInExpandTime,CheckOutExpandTime,ComeLateExpandTime,LeaveEarlyExpandTime")] WorkingShift workingShift)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workingShift).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Name", workingShift.EmployeeId);
            ViewBag.StoreId = new SelectList(db.Stores, "ID", "Name", workingShift.StoreId);
            return View(workingShift);
        }

        // GET: WorkingShifts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkingShift workingShift = db.WorkingShifts.Find(id);
            if (workingShift == null)
            {
                return HttpNotFound();
            }
            return View(workingShift);
        }

        // POST: WorkingShifts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkingShift workingShift = db.WorkingShifts.Find(id);
            db.WorkingShifts.Remove(workingShift);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web-admin/Admin_Page/Views/WorkingShifts/Delete.cshtml
@model Admin_Page.WorkingShift

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkingShift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckMin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalWorkTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalWorkTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShiftStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShiftStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShiftEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShiftEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatePerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatePerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcessingStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcessingStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeFramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeFramId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BreakTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreakTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedCheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedCheckOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedCheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedCheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsRequested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsRequested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovePerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovePerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoteRequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteRequest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastCheckBeforeShift)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastCheckBeforeShift)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstCheckAfterShift)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstCheckAfterShift)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOverTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOverTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InMode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InMode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OutMode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OutMode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BreakCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreakCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOutExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOutExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ComeLateExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComeLateExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveEarlyExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveEarlyExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Store.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web-admin/Admin_Page/Views/WorkingShifts/Details.cshtml
@model Admin_Page.WorkingShift

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WorkingShift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckMin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalWorkTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalWorkTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShiftStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShiftStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShiftEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShiftEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatePerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatePerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProcessingStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProcessingStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeFramId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeFramId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BreakTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreakTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedCheckOut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedCheckOut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestedCheckIn)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestedCheckIn)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsRequested)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsRequested)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovePerson)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovePerson)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NoteRequest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NoteRequest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastCheckBeforeShift)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastCheckBeforeShift)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstCheckAfterShift)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstCheckAfterShift)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOverTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOverTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InMode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InMode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OutMode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OutMode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BreakCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BreakCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckOutExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckOutExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ComeLateExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComeLateExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveEarlyExpandTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveEarlyExpandTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employee.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Store.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Store.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Web-admin/Admin_Page/Views/WorkingShifts/Index.cshtml
@model IEnumerable<Admin_Page.WorkingShift>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>WorkingShifts Management</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Html.BeginForm("Index", "WorkingShifts", FormMethod.Get, new { @class = "dataTables_length d-flex" }))
        {
            @Html.DropDownList("Stores", (IEnumerable<SelectListItem>)ViewBag.CategoryList, "Select store", new { @onchange = "this.form.submit();", @class = "custom-select custom-select-sm form-control form-control-sm" })
        }
    </div>
</p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.CheckMin)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.CheckMax)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalWorkTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.ShiftStart)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.ShiftEnd)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.CheckInTime)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.UpdatePerson)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.ProcessingStatus)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.TimeFramId)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.BreakTime)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.RequestedCheckOut)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.RequestedCheckIn)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.IsRequested)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.ApprovePerson)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.NoteRequest)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.LastCheckBeforeShift)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.FirstCheckAfterShift)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.IsOverTime)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.InMode)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.OutMode)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.BreakCount)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.CheckInExpandTime)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.CheckOutExpandTime)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.ComeLateExpandTime)
            </th>
            <th hidden>
                @Html.DisplayNameFor(model => model.LeaveEarlyExpandTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employee.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Store.Name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.CheckMin)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.CheckMax)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalWorkTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.ShiftStart)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.ShiftEnd)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.CheckInTime)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.UpdatePerson)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.ProcessingStatus)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.TimeFramId)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.BreakTime)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.RequestedCheckOut)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.RequestedCheckIn)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.IsRequested)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.ApprovePerson)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.NoteRequest)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.LastCheckBeforeShift)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.FirstCheckAfterShift)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.IsOverTime)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.InMode)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.OutMode)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.BreakCount)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.CheckInExpandTime)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.CheckOutExpandTime)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.ComeLateExpandTime)
                </td>
                <td hidden>
                    @Html.DisplayFor(modelItem => item.LeaveEarlyExpandTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Employee.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Store.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>